#!/bin/bash

# helper that compiles gtk program as per directions here:
# https://developer.gnome.org/gtk3/3.2/gtk-getting-started.html

# usage ./gtkcc foo foo.c
# foo.c is the source file, and foo will be the compiled executable

# shortcut ./gtkcc foo.c will generate foo as the executable 

paramsSent=$#

if [ "$paramsSent" -eq 2 ]
then
  #test second arg for .c file ext
  if [ ${2: -2}  == ".c" ]
  then 
    compiled=$1
    source=$2
  else
    echo "Source file must have a .c extension"
    exit 2
  fi
elif [ "$paramsSent" -eq 1 ]
then
  #test first arg for .c file ext
  if [ ${1: -2}  == ".c" ]
  then
    source=$1
    # chomp off the file ext
    compiled="${source%.*}"
  else
    echo "no valid source specified"
    exit 2
  fi
else
  echo "invalid number of args"
  exit 2
fi

gcc `pkg-config --cflags gtk+-3.0` -o $compiled $source `pkg-config --libs gtk+-3.0`
